"""task

Revision ID: 48778c9365cd
Revises: 68ccd8c84b48
Create Date: 2024-05-18 14:56:08.847519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48778c9365cd'
down_revision: Union[str, None] = '68ccd8c84b48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tasks',
    sa.Column('task_uid', sa.UUID(), nullable=False),
    sa.Column('user_uid', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('completed_date_utc', sa.DateTime(), nullable=True),
    sa.Column('date_created_utc', sa.DateTime(), nullable=True),
    sa.Column('date_updated_utc', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_uid'], ['users.user_uid'], ),
    sa.PrimaryKeyConstraint('task_uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Tasks')
    # ### end Alembic commands ###
